# Generated by Django 4.2.7 on 2025-11-08 14:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('channel_type', models.CharField(choices=[('text', 'Text Channel'), ('voice', 'Voice Channel'), ('announcement', 'Announcement Channel'), ('stage', 'Stage Channel')], default='text', max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('is_nsfw', models.BooleanField(default=False)),
                ('slowmode_delay', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'channels',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
