# Generated by Django 4.2.7 on 2025-11-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ('meshup_channels', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_channels', to='meshup_channels.channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='servers.server'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['server', 'position'], name='channels_server__9628c2_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['server', 'channel_type'], name='channels_server__5593f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('server', 'name')},
        ),
    ]
