# Generated by Django 4.2.7 on 2025-11-08 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_level', models.CharField(choices=[('all', 'All Messages'), ('mentions', 'Only Mentions'), ('nothing', 'Nothing')], default='all', max_length=20)),
                ('mute_server', models.BooleanField(default=False)),
                ('mute_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='ServerSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_notifications', models.BooleanField(default=True)),
                ('explicit_content_filter', models.BooleanField(default=True)),
                ('verification_level', models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Highest')], default=0)),
                ('require_2fa_for_admin', models.BooleanField(default=False)),
                ('auto_moderation', models.BooleanField(default=False)),
                ('banned_words', models.JSONField(blank=True, default=list)),
                ('enable_tasks', models.BooleanField(default=True)),
                ('enable_notes', models.BooleanField(default=True)),
                ('enable_events', models.BooleanField(default=True)),
                ('enable_polls', models.BooleanField(default=True)),
                ('max_members', models.IntegerField(default=100)),
                ('max_channels', models.IntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'server_settings',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='dark', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ja', 'Japanese')], default='en', max_length=5)),
                ('compact_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('desktop_notifications', models.BooleanField(default=True)),
                ('notification_sound', models.BooleanField(default=True)),
                ('notify_messages', models.BooleanField(default=True)),
                ('notify_mentions', models.BooleanField(default=True)),
                ('notify_tasks', models.BooleanField(default=True)),
                ('notify_events', models.BooleanField(default=True)),
                ('notify_polls', models.BooleanField(default=True)),
                ('show_online_status', models.BooleanField(default=True)),
                ('allow_direct_messages', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=False)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
    ]
