# Generated by Django 4.2.7 on 2025-11-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meshup_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_6193b2_idx',
            old_name='audit_logs_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_bcaa71_idx',
            old_name='audit_logs_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_severit_fc52cc_idx',
            old_name='audit_logs_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_resourc_bda8a6_idx',
            old_name='audit_logs_resource_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_email_e3bad1_idx',
            old_name='login_attempts_email_created_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_ip_addr_d06a3f_idx',
            old_name='login_attempts_ip_created_idx',
        ),
    ]
