# Generated by Django 4.2.7 on 2025-11-08 14:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('server', 'Server Management'), ('channel', 'Channel Management'), ('message', 'Message Management'), ('task', 'Task Management'), ('note', 'Note Management'), ('event', 'Event Management'), ('poll', 'Poll Management'), ('member', 'Member Management')], max_length=20)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('role_type', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('member', 'Member'), ('guest', 'Guest'), ('custom', 'Custom Role')], default='custom', max_length=20)),
                ('color', models.CharField(default='#99AAB5', max_length=7)),
                ('is_mentionable', models.BooleanField(default=True)),
                ('is_hoisted', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['-position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServerMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_deafened', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='members', to='roles.role')),
            ],
            options={
                'db_table': 'server_members',
                'ordering': ['-joined_at'],
            },
        ),
    ]
