# Generated by Django 4.2.7 on 2025-11-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='roles.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='servers.server'),
        ),
        migrations.AddIndex(
            model_name='servermember',
            index=models.Index(fields=['user', 'server'], name='server_memb_user_id_d5167f_idx'),
        ),
        migrations.AddIndex(
            model_name='servermember',
            index=models.Index(fields=['server', 'is_banned'], name='server_memb_server__413c6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servermember',
            unique_together={('user', 'server')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['server', 'position'], name='roles_server__2b0c8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('server', 'name')},
        ),
    ]
