# Generated by Django 4.2.7 on 2025-11-08 14:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='server_icons/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='server_banners/')),
                ('region', models.CharField(choices=[('us-east', 'US East'), ('us-west', 'US West'), ('eu-central', 'EU Central'), ('asia-pacific', 'Asia Pacific')], default='us-east', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('verification_level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'servers',
                'ordering': ['-created_at'],
            },
        ),
    ]
