# Generated by Django 4.2.7 on 2025-11-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['owner'], name='servers_owner_i_f13690_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['is_public'], name='servers_is_publ_607c7e_idx'),
        ),
    ]
