# Generated by Django 4.2.7 on 2025-11-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_serverinvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='serverinvite',
            new_name='server_invi_server__30c72f_idx',
            old_name='server_invites_server_created_idx',
        ),
        migrations.RenameIndex(
            model_name='serverinvite',
            new_name='server_invi_code_c020b4_idx',
            old_name='server_invites_code_idx',
        ),
    ]
