# Generated by Django 4.2.7 on 2025-11-08 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('deadline', 'Deadline'), ('announcement', 'Announcement'), ('milestone', 'Milestone'), ('reminder', 'Reminder'), ('other', 'Other')], default='meeting', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], db_index=True, default='scheduled', max_length=20)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True, help_text='Virtual meeting link')),
                ('recurrence_type', models.CharField(choices=[('none', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='none', max_length=20)),
                ('recurrence_end_date', models.DateTimeField(blank=True, null=True)),
                ('recurrence_interval', models.IntegerField(default=1, help_text='Interval for recurrence (e.g., every 2 weeks)')),
                ('reminder_minutes_before', models.JSONField(default=list, help_text='List of minutes before event to send reminders [15, 60, 1440]')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('color', models.CharField(default='#3498db', help_text='Hex color for calendar display', max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('attending', 'Attending'), ('not_attending', 'Not Attending'), ('maybe', 'Maybe'), ('tentative', 'Tentative')], default='pending', max_length=20)),
                ('is_organizer', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False, help_text='Required attendee vs optional')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Attendee notes or comments')),
                ('invited_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'event_attendees',
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minutes_before', models.IntegerField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.event')),
            ],
            options={
                'db_table': 'event_reminders',
            },
        ),
    ]
