# Generated by Django 4.2.7 on 2025-11-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ('meshup_channels', '0002_initial'),
        ('events', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendees', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events_attending', through='events.EventAttendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='meshup_channels.channel'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='servers.server'),
        ),
        migrations.AlterUniqueTogether(
            name='eventreminder',
            unique_together={('event', 'user', 'minutes_before')},
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['event', 'rsvp_status'], name='event_atten_event_i_b8d724_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['server', 'start_time'], name='events_server__2700be_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time', 'end_time'], name='events_start_t_9c99d7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_status_8890b6_idx'),
        ),
    ]
