# Generated by Django 4.2.7 on 2025-11-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteversion',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteversion',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='notes.note'),
        ),
        migrations.AddField(
            model_name='notecollaborator',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='notes.note'),
        ),
        migrations.AddField(
            model_name='notecollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='last_edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='servers.server'),
        ),
        migrations.AddIndex(
            model_name='noteversion',
            index=models.Index(fields=['note', '-version_number'], name='note_versio_note_id_530ae0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='noteversion',
            unique_together={('note', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='notecollaborator',
            unique_together={('note', 'user')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['server', '-updated_at'], name='notes_server__171cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['server', 'is_pinned'], name='notes_server__7b7d66_idx'),
        ),
    ]
